[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --cov=.
    --cov-report=html
    --cov-report=term-missing
    --ignore=tests
    --cov-config=.coveragerc

[coverage:run]
omit =
    tests/*
    */__pycache__/*
    */venv/*
    */site-packages/*
    setup.py
